Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,14 @@ jobs:
       run: |
         # SSH into the EC2 instance and deploy the code
         ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_IP }} << 'EOF'
+          # Check if Git is installed, and install it if not
+          if ! command -v git &> /dev/null
+          then
+            echo "Git not found, installing..."
+            sudo yum install -y git  # For Amazon Linux
+            # sudo apt-get install git  # For Ubuntu (uncomment if using Ubuntu on EC2)
+          fi
+
           # Navigate to the directory where your code is located
           cd /var/www/html/gynic/gynic
 
